sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.21.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - ./tentags test-jenkins

after_success:
  - bash cp api-cdn/luacov.reports.out luacov.report.out
  - bash <(curl -s https://codecov.io/bash) -t 36b8954b-c8d2-451a-b8ac-a8bc9ab5ebe5
