version: '2'
services:
  filtta:
    build: api-cdn/.
    ports:
      - "80:80"
      - "81:8081"
    entrypoint: ""
    command:  bash -c "lapis server"
    links:
      - redis-general
      - redis-comment
      - redis-user
    env_file:
      - filtta.env

  imgprocess:
    tty: true
    links:
      - redis-general
    entrypoint: ""
    command: luajit imgconverter.lua
  redis-general:
    build: redis
    volumes:
      - ./redis/general:/data
    expose:
      - '6379'
  redis-comment:
    build: redis
    volumes:
      - ./redis/comment:/data
    expose:
      - '6379'
  redis-user:
    build: redis
    volumes:
      - ./redis/user:/data
    expose:
      - '6379'
