version: '2'
services:
  filtta:
    image: kraftman/tentags.io:test
    #build: 
    #  context: api-cdn/.
    #  dockerfile: test.Dockerfile
    entrypoint: ""
    #command:  bash -c "busted -o junit -c testing/unit > test.xml"
    command:  bash -c "busted -R -c testing/unit/*"
    links:
      - redis-general
      - redis-comment
      - redis-user
    env_file:
      - filtta-test.env
  redis-general:
    build: redis
    volumes:
      - ./redis/general:/data
    expose:
      - '6379'
  redis-comment:
    build: redis
    volumes:
      - ./redis/comment:/data
    expose:
      - '6379'
  redis-user:
    build: redis
    volumes:
      - ./redis/user:/data
    expose:
      - '6379'
