version: '2'
services:
  filtta:
    build: api-cdn/.
    volumes:
      - ./api-cdn:/opt/openresty/nginx/conf
    env_file:
      - filtta.env
  imgprocess:
    privileged: true
    build: imgprocess/.
    volumes:
     - ./imgprocess/lua:/lua
    env_file:
     - filtta.env

  imghost:
    image: tenstartups/openresty
    volumes:
     - ./imghost:/imghost
     - ./www:/var/www
    entrypoint: ["nginx", "-c", "/imghost/nginx/conf/nginx.conf", "-p", "/imghost/nginx/"]
  backup:
    build: backup/.
    volumes:
     - ./backup:/usr/src/app
     - ./redis:/data
    command: ['nodemon', 'server.js']
  # phantom:
  #   image: cmfatih/phantomjs
  #   volumes:
  #     - ./phantom:/phantom

networks:
  default:
    external:
      name: webserver_default
