version: '2'
services:
  filtta:
    build: api-cdn/.
    volumes:
      - ./api-cdn:/usr/local/openresty/nginx/conf
    env_file:
      - filtta.env
    restart: always
  imgprocess:
    privileged: true
    build: imgprocess/.
    volumes:
     - ./imgprocess/lua:/lua
    env_file:
     - filtta.env
  #backup:
  #  build: backup/.
  #  volumes:
  #   - ./backup:/usr/src/app
  #   - ./redis:/data
  #  command: ['nodemon', 'server.js']
  # phantom:
  #   image: cmfatih/phantomjs
  #   volumes:
  #     - ./phantom:/phantom

networks:
  default:
    external:
      name: webserver_default
