version: '2'
services:
  filtta:
    build: api-cdn/.
    ports:
      - "80:8080"
      - "8081:8081"
    links:
      - imghost
      - redis-general
      - redis-comment
      - redis-user
    volumes:
      - ./api-cdn:/opt/openresty/nginx/conf
    entrypoint: ""
    command:  bash -c "lapis server"
    environment:
      - DISABLE_CACHE=true
      - DISABLE_RATELIMIT=true
      - UNLIMITED_VOTING=true
      - EMAIL_CREDENTIALS=831q&0AP3Y9w

  imghost:
    image: tenstartups/openresty
    expose:
      - "80"
    volumes:
     - ./imghost:/imghost
     - ./www:/var/www
    entrypoint: ["nginx", "-c", "/imghost/nginx/conf/nginx.conf", "-p", "/imghost/nginx/"]
  imgprocess:
    privileged: true
    build: imgprocess/.
    volumes:
     - ./imgprocess/lua:/lua
     - ./www:/var/www
    links:
      - redis-general
  redis-general:
    build: redis
    volumes:
      - ./redis/general:/data
    expose:
      - '6379'
  redis-comment:
    build: redis
    volumes:
      - ./redis/comment:/data
  redis-user:
    build: redis
    volumes:
      - ./redis/user:/data
  phantom:
    image: cmfatih/phantomjs
    volumes:
      - ./phantom:/phantom

networks:
  default:
    external:
      name: webserver_default
