version: '2'
services:
  api-cdn:
    build: api-cdn/.
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    links:
      - imghost
    volumes:
      - ./api-cdn:/opt/openresty/nginx/conf
    entrypoint: ""
    command:  bash -c "lapis server"

  imghost:
    image: tenstartups/openresty
    ports:
      - "81:80"
    volumes:
     - ./imghost:/imghost
     - ./www:/var/www
    entrypoint: ["nginx", "-c", "/imghost/nginx/conf/nginx.conf", "-p", "/imghost/nginx/"]
  imgprocess:
    build: imgprocess/.
    volumes:
     - ./imgprocess/lua:/lua
     - ./www:/var/www
    links:
      - redis-general
  redis-general:
    build: redis
    volumes:
      - ./redis/general:/data
  redis-comment:
    build: redis
    volumes:
      - ./redis/comment:/data
  redis-user:
    build: redis
    volumes:
      - ./redis/user:/data

networks:
  default:
    external:
      name: taggr_net
