version: '2'
services:
  filtta:
    build: api-cdn/.
    ports:
      - "80:8080"
      - "8081:8081"
    links:
      - imghost
      - redis-general
      - redis-comment
      - redis-user
    volumes:
      - ./api-cdn:/opt/openresty/nginx/conf
    entrypoint: ""
    command:  bash -c "lapis server"
    environment:
      - DISABLE_CACHE=true
      - DISABLE_RATELIMIT=true
      - EMAIL_CREDENTIALS=831q&0AP3Y9w

  imghost:
    image: tenstartups/openresty
    expose:
      - "80"
    volumes:
     - ./imghost:/imghost
     - ./www:/var/www
    entrypoint: ["nginx", "-c", "/imghost/nginx/conf/nginx.conf", "-p", "/imghost/nginx/"]
  imgprocess:
    privileged: true
    build: imgprocess/.
    volumes:
     - ./imgprocess/lua:/lua
     - ./www:/var/www
    links:
      - redis-general
  redis-general:
    build: redis
    volumes:
      - ./redis/general:/data
    expose:
      - '6379'
  redis-comment:
    build: redis
    volumes:
      - ./redis/comment:/data
  redis-user:
    build: redis
    volumes:
      - ./redis/user:/data
  phantom:
    image: cmfatih/phantomjs
    volumes:
      - ./phantom:/phantom
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    depends_on:
      - elasticsearch2
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
  search:
    build: search/.
    depends_on:
      - elasticsearch1
      - elasticsearch2
    volumes:
      - ./search:/search

networks:
  default:
    external:
      name: webserver_default
