version: '2'
services:
  api-cdn:
    build: api-cdn/.
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    links:
      - imghost
    volumes:
      - ./api-cdn:/opt/openresty/nginx/conf
    entrypoint: ""
    command:  bash -c "lapis server"
  imghost:
    image: tenstartups/openresty
    ports:
      - "81:80"
    volumes:
     - ./imghost:/imghost
     - ./www:/var/www
    entrypoint: ["nginx", "-c", "/imghost/nginx/conf/nginx.conf", "-p", "/imghost/nginx/"]
  imgprocess:
    build: imgprocess/.
    volumes:
     - ./imgprocess:/imgprocess
     - ./www:/var/www
  redis-general:
    build: redis
    volumes:
      - ./redis/general:/bitnami/redis
  redis-comment:
    build: redis
    volumes:
      - ./redis/comment:/bitnami/redis
  redis-user:
    build: redis
    volumes:
      - ./redis/user:/bitnami/redis

networks:
  default:
    external:
      name: taggr_net
