version: 2
jobs:
  build:
    machine: true
    docker:
      - image: moregreenhouse/tm-base
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            pwd
            ls
            chmod +x tentags
            sh ./tentags test-jenkins 
            cp api-cdn/luacov.reports.out luacov.report.out
            bash <(curl -s https://codecov.io/bash)

